### PR TITLE
Use prepend over chaining

### PR DESCRIPTION
**Pull request by 8398a7**
refs #6, #7 

#6 has some mistakes.
In replacing with prepend, I issue PR as a minimal change.

### CODE REVIEW

**Comment by qrush** [comment]
+1 - would love to get some more warnings out of my app. ❤️  🙏  cc @dewski @lucasmazza

**Comment by dewski** [comment]
Thank you @8398a7! I'll cut a release shortly.

**Comment by qrush** [comment]
@dewski thank you! would appreciate a look at @8398a7's peek/peek-rblineprof#15 too. 🙇

**Comment by dewski** [comment]
Bumped to [v1.3.0](https://github.com/peek/peek-pg/releases/tag/v1.3.0)

**Comment by lucasmazza** [comment]
@dewski thanks! ❤️

**Pull request merged**
